### ISSUE TITLE
Split out OPRF functionality?

### ISSUE THREAD

**Issue by chris-wood** [stef/libopaque#22]
Is there interest in splitting out the OPRF implementation in this library to a separate repository? I'd like to list this implementation on the [specification page](https://github.com/cfrg/draft-irtf-cfrg-voprf/#existing-implementations). Alternatively, we could list this as an integration [on that same page](https://github.com/cfrg/draft-irtf-cfrg-voprf/#other-integrations).

**Comment by stef** [comment]
thanks for the interesting question. i think this will happen, let's keep this issue open, and list this on the integration list until then.

**Comment by chris-wood** [comment]
Sounds good! Would you mind sending a PR to add your implementation to the list?

**Comment by stef** [comment]
done!

**Comment by stef** [comment]
i did not remove it yet from libopaque, but there is now this: https://github.com/stef/liboprf/ - which also contains a threshold oprf!

please close this issue at your earliest convenience if you agree this solves the issue. or wait until the redundancy of the oprf functions is removed from libopaque. either way is good.

**Comment by stef** [comment]
this should now be complete with this commit https://github.com/stef/libopaque/commit/a4209e3319718d1c72b9d1c2147ecd03a5e2ff97 - if you disagree please reopen this issue.

**Comment by stef** [comment]
for reference my ordeal started at this commit https://github.com/stef/libopaque/commit/ed79da5b86a0940bdc3e4895d6fdd7d42c2e34f9
