### ISSUE TITLE
Error when run "make" command

### ISSUE THREAD

**Issue by sofiawong** [stef/libopaque#24]
![image](https://user-images.githubusercontent.com/24559709/174429373-84ab50ae-fc30-47b1-adf8-65f3786989e0.png)

Hi, I face this issue. I appreciate if anyone can help me resolve. I have already install opaque using pip but it raises an error that they could not find libsodium which explains why I following additional installation instructions in libopaque repo!
Thank you!

**Comment by stef** [comment]
you need to download and unpack latest libsodium-*-mingw.tar.gz and unpack it. 'https://download.libsodium.org/libsodium/releases/' and then set -I to where the includes are and -L to where the dlls are.

**Comment by sofiawong** [comment]
Hi, thanks for the reply. May I know what is the command for -l and -L?

**Comment by sofiawong** [comment]
![image](https://user-images.githubusercontent.com/24559709/174450191-76c4b4d3-f552-41dd-9d05-3b65bccc1c87.png)
I have already installed libsodium. It resides in /usr/include and I make a symbolic link
`ln -s /usr/include/sodium.h sodium.h to libopaque/src directory`

but it is still not working

**Comment by stef** [comment]
i'm confused. in your screenshot it says your CC is mingw, and then you say you have sodium.h already in /usr/include. for what arch are you trying to compile?

**Comment by stef** [comment]
anyway i updated the makefile, if you drop mingw64 sodium into win/libsodium-win64 then make mingw64 should work for your. see the commit https://github.com/stef/libopaque/commit/39b6a00c6f0098cc7d1c5b29f0fe8a1bf7429f7f

**Comment by sofiawong** [comment]
@stef , while running "make", "sodium.h" not found is solved but another error popped up.

![image](https://user-images.githubusercontent.com/24559709/174531498-e6aae86a-f138-44f2-97af-3e017e3bff02.png)

**Comment by stef** [comment]
you don't really need the munit tests, do you?

**Comment by sofiawong** [comment]
Yea, I wanted to ignore it. But, they can't find this library which I already pip installed it.

![image](https://user-images.githubusercontent.com/24559709/174597075-48d11600-1dda-4f3d-a114-798ddb35b930.png)

**Comment by stef** [comment]
on what operating system are you? why are you using mingw?

**Comment by stef** [comment]
then why do you use mingw as a compiler suite?

**Comment by stef** [comment]
mingw compiles for windows

**Comment by sofiawong** [comment]
the error said they couldnt find mingw, so I installed it.

**Comment by sofiawong** [comment]
@stef , thanks for the fix.

I have no issues running make command but the library still isnt found.

![image](https://user-images.githubusercontent.com/24559709/174704116-a31d22da-7c3e-47c1-a113-67cedc6203b0.png)

**Comment by stef** [comment]
also did you do make install? i recommend
```
sudo PREFIX=/usr make  install
sudo ldconfig
```

**Comment by sofiawong** [comment]
@stef , in addition, I had to install pysodium. Thanks for the help. Have a good week ahead!

**Comment by sofiawong** [comment]
@stef , sorry to bother again. May I know what is the encoding used for the byte string for python? As I am using graphql, it does not support robust output return. It will return it as a string.
![image](https://user-images.githubusercontent.com/24559709/175847186-c92b05fa-e7ec-452f-ba47-698b3b6f3eb3.png)

**Comment by stef** [comment]
it's just binary bytes. i recommend just base64-ing them.
