### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by sudeep-moharana-idnow** [stef/libopaque#34]
Hi, 

While running the make command I'm getting the following error. Can you please help me resolve this? I am on mac 13.2 with intel processor.

`gcc -shared -march=native -Wall -O2 -g -fstack-protector-strong -D_FORTIFY_SOURCE=2 -fasynchronous-unwind-tables -fpic -fstack-clash-protection -fcf-protection=full -Werror=format-security -Werror=implicit-function-declaration -Wl,-z,defs -Wl,-z,relro -ftrapv -Wl,-z,noexecstack  -Iaux_ -Wl,-soname,libopaque.so -o libopaque.so common.o opaque.o aux_/kdf_hkdf_sha512.o -g -lsodium
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libopaque.so] Error 1`

**Comment by stef** [comment]
hmm, seems you use clang? which version of clang? newer versions do support -z afaik.

**Comment by sudeep-moharana-idnow** [comment]
I am on clang version 14

**Comment by stef** [comment]
it seems - according to the internet - -z is a gnu ld thing, and not supported by macos clang ld.

you can also just adjust the flags, and remove those -z linker flags. they will disable security protections, but will otherwise work. you need to find out what kind of link time flags exist on your system that provide similar security features as those that you removed, or even better ones.

or you could use gnu ld.

**Comment by sudeep-moharana-idnow** [comment]
I was able to build this which basically creates libopaque.so in my lib. However the python library which calls ctypes.util.find_library('opaque') or ctypes.util.find_library('libopaque') fails because cytype.util.find_library is looking for the following. 
`elif os.name == "posix" and sys.platform == "darwin":
    from ctypes.macholib.dyld import dyld_find as _dyld_find
    def find_library(name):
        possible = ['lib%s.dylib' % name,
                    '%s.dylib' % name,
                    '%s.framework/%s' % (name, name)` 
since this one is of type .so, the function returns none. Is there a way to generate a .dylib file?

**Comment by stef** [comment]
sorry, i have zero experience or access to apple products. although this seems to be an easy problem that is probably solved by many other projects already, it should be easy to find such and test those, i am happy to accept pull requests!

**Comment by stef** [comment]
closing this issue, please reopen if you disagree with this decision.
