### ISSUE TITLE
The password should never be disclosed to the server

### ISSUE THREAD

**Issue by odiferousmint** [stef/libopaque#37]
Hello.

According to https://github.com/stef/libopaque/blob/master/src/utils/man/opaque.md:

> Initializing OPAQUE (registration) can be done either online or offline. The online variant has the benefit that the server never learns anything about the users password, with the drawback that this requires 3 messages to be exchanged by the client and the server.

> The offline initialization is much easier, however either the user learns the servers secret, or the server learns the users password. The latter might be useful if some organisation wants to enforce some password quality rules and check those upon registration. The drawback is that either way, some sensitive information leaks to the other party.

This is not supposed to be true.

https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-opaque

> OPAQUE provides forward secrecy with respect to password leakage while also hiding the password from the server, even during password registration.

> clients never disclose their passwords to the server, even during registration

> Some applications may require learning the client's password for enforcing password rules. Doing so invalidates this important security property of OPAQUE and is NOT RECOMMENDED. Applications should move such checks to the client.

[...]

**Comment by stef** [comment]
well, depends. yes, if you only implement the cfrg spec. which only specifies the online registration, then you are right. however the original opaque paper instead only described the offline registration, which is not specified by the cfrg, but is implemented by libopaque.

**Comment by stef** [comment]
please close this issue, if this answers your question.

**Comment by stef** [comment]
see also: https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/434
